spring:
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASS}
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_ID}
            client-secret: ${GOOGLE_SECRET}
            scope: profile, email
            redirect-uri: ${SERVER_ORIGIN}/login/oauth2/code/google
    jwt:
      secret: ${JWT_SECRET}
    cors:
      client-origin: ${CLIENT_ORIGIN}

server:
  port: ${PORT}

logging:
  level:
    org:
      springframework:
        security: DEBUG